services:
   appsmith:
     image: index.docker.io/appsmith/appsmith-ee:v1.99
     container_name: appsmith
     ports:
         - "80:80"
         - "443:443"
     volumes:
         - ./stacks:/appsmith-stacks
     restart: unless-stopped