services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${PLEX_DATA_PATH}/plex/library:/config
      - ${PLEX_DATA_PATH}/tvseries:/tv
      - ${PLEX_DATA_PATH}/movies:/movies
    # ports:
    #   - "32400:32400"
    #   - "32469:32469"
    restart: unless-stopped