version: '3.3'
services:
    traefik:
        container_name: traefik
        ports:
            - '8080:8080'
            - '80:80'
        volumes:
            # - '$PWD/traefik.yml:/etc/traefik/traefik.yml'
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: 'traefik:latest'
