services:
  code-server:
    image: codercom/code-server:4.96.2-39
    container_name: code-server
    environment:
      - DOCKER_USER=$USER
      - PASSWORD=mypassword #Replace this with your login password
    volumes:
      - ./config:/config
      - $PWD:/home/coder/workspace
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
    - code-server
    user: ${UID}:${GID} 

networks:
    code-server:
      driver: bridge
