services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

  server:
    image: rancher/rancher:latest
    container_name: rancher-server
    privileged: true 
    environment:
      - CATTLE_BOOTSTRAP_PASSWORD=admin
    volumes:
      - ./rancher-data:/var/lib/rancher
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rancher.rule=Host(`rancher.localhost`)"
      - "traefik.http.routers.rancher.entrypoints=websecure"
      - "traefik.http.routers.rancher.tls=true"
      #- "traefik.http.services.rancher.loadbalancer.server.port=443"
      - "traefik.http.services.rancher.loadbalancer.server.port=80"

volumes:
  rancher-data: