# Step 1 : Create a volume for portainer data
         # command: docker create volume portainer_data
# Step 2: run => docker compose up -d
version: '3.3'
services:
    portainer-ce:
        ports:
            - '8000:8000'
            - '9443:9443'
        container_name: portainer
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'portainer_data:/data'
        image: 'portainer/portainer-ce:2.9.3'