version: '2'

services:
  memsql:
    image: 'memsql/cluster-in-a-box'
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: ${LICENSE_KEY}
      ROOT_PASSWORD: 'password'
      START_AFTER_INIT: 'Y'
    networks: 
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
